fix remove_edges_from called with view
when `g.remove_edges_from()` is called with a view as an argument,
such as `g.out_edges(n)`, a RuntimeError is raised:

RuntimeError: dictionary changed size during iteration

removal changes the view.

can be worked around by creating a list:

`g.remove_edges_from(list(g.out_edges(n)))`